# Generated by Django 3.2.9 on 2022-01-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0002_auto_20220104_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rank',
            new_name='charts',
        ),
    ]
