# Generated by Django 3.2.9 on 2022-01-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0003_rename_rank_charts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
