# Generated by Django 3.2.9 on 2022-01-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='naverid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='naverscore',
            field=models.FloatField(null=True),
        ),
    ]
