# Generated by Django 3.2.9 on 2022-01-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0002_auto_20220104_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=200),
        ),
    ]
