# Generated by Django 3.2.9 on 2022-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themovieDB', '0003_alter_movie_original_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
